### ISSUE TITLE
Separate config file into static and scenario config files

### ISSUE THREAD

**Issue by rjhanes** [NREL/celavi#93]
See PR #85 for initial discussion

Goal: Make it easier for CELAVI users to parse the config file by separating it into a "case study config" file with values that are set once for a case study and a "scenario definition" config file with parameters that are changed to define different scenarios for a case study. A suggested config file split is given at the bottom of this comment.

Steps towards implementation are as follows (subject to revision):
1. Add an argument to specify the scenario definition config
2. Read in variables from both config and combine programmatically into a single "config" dictionary to minimize refactoring
3. Refactor variable group names as needed - if we keep variable group names unchanged from the original single config file, then this is also minimized
4. Test & debug, etc

## Case study config
```
model_run:
    start_year: 2000
    end_year: 2050
    timesteps_per_year: 12
    min_lifespan: 120 # Units: timesteps
    # lcia_update_timesteps : 12 #Not implemented yet
    cg_update_timesteps: 12

data_directories:
    inputs: inputs/
    raw_locations: inputs/raw_location_data/
    us_roads: inputs/precomputed_us_road_network/
    preprocessing_output: preprocessing/
    lookup_tables: lookup_tables/
    lci: pylca_celavi_data/
    outputs: outputs/
    routing_output: preprocessing/routing_intermediate_files/

input_filenames:
    locs: locations_computed.csv
    step_costs: step_costs.csv
    fac_edges: fac_edges.csv
    transpo_edges: transpo_edges.csv
    route_pairs: route_pairs.csv
    avg_blade_masses: avgblademass.csv
    routes_custom: routes.csv
    routes_computed: routes_computed.csv
    transportation_graph: transportation_graph.csv
    node_locs: node_locations.csv
    power_plant_locs: uswtdb_v4_1_20210721.csv # This is updated relatively infrequently
    landfill_locs: landfilllmopdata.csv
    other_facility_locs: other_facility_locations_all_us.csv
    # standard scenario file is now compiled from the standard_scenario string variable
    lookup_facility_type: facility_type.csv
    lookup_step_costs: step_costs_default.csv
    turbine_data: number_of_turbines.csv

output_filenames:
    costgraph_pickle: netw.obj
    costgraph_csv: netw.csv
    pathway_cost_history: pathway_cost_history.csv
    component_counts_plot: component_counts.png
    material_mass_plot: material_mass.png
    count_cumulative_histories: count_cumulative_histories.csv
    mass_cumulative_histories: mass_cumulative_histories.csv
```

## Scenario definition config
```
flags:
  compute_locations     : True  # if compute_locations is enabled (True), compute locations from raw input files (e.g., LMOP, US Wind Turbine Database)
  run_routes            : True  # if run_routes is enabled (True), compute routing distances between all input locations
  use_computed_routes   : True  # if use_computed_routes is enabled, read in a pre-assembled routes file instead of generating a new one
  initialize_costgraph  : True  # create cost graph fresh or use an imported version
  enable_data_filtering : False  # If true, dataset will be filtered to the states below
  pickle_costgraph      : True  # save the newly initialized costgraph as a pickle file
  generate_step_costs   : True # set to False if supply chain costs for a facility type vary regionally
  use_fixed_lifetime    : True # set to False to use Weibull distribution for lifetimes

scenario_parameters:
    standard_scenario: MidCase # @TODO Need to add a line of code to compile the standard scenario file name in main.py
    # If you specify enable_data_filtering = True above, you need to list the states to filter here.
    # Default behavior is not to pass any states through the filter.
    # If enable_data_filtering is False, this list is ignored.
    states_to_filter:
    - IA
    component_list:
        nacelle : 1
        blade : 3
        tower : 1
        foundation : 1
    material_list:
        - glass fiber
        - epoxy
    seed: 13
    blade_weibull_L: 240
    blade_weibull_K: 2.2
    component_fixed_lifetimes:
        nacelle : 30
        blade : 20
        foundation : 50
        tower : 50
    sc_begin: manufacturing
    sc_end: 
        - landfilling
        - cement co-processing
        - next use
    cost_parameters:
        finegrind_cumul_initial: 1.0
        finegrind_initial_cost: 165.38
        finegrind_revenue: 242.56
        finegrind_learnrate: -0.05
        finegrind_material_loss: 0.3
        coarsegrind_cumul_initial: 1.0
        coarsegrind_initial_cost: 121.28
        coarsegrind_learnrate: -0.05
    cg_verbose: 1
    save_cg_csv: True
```
